### ISSUE TITLE
Conflicts of MIT license with Terms of Use

### ISSUE THREAD

**Issue by ForeverZer0** [xml-to-go/xml-to-go.github.io#2]
The current license (MIT) is in contradictory to the terms of use listed in the README. Would it be possible to simply replace the incorrect license with one that has those restrictions amended, or edit the terms of use to not be contradictory of it?

As it stands, nearly every persons who uses or has ever used this project or web-service is in inadvertently in violation of its terms of use.

**Comment by xhit** [comment]
You can use the commit before the README update https://github.com/xml-to-go/xml-to-go.github.io/tree/ce325e4da331dd85229212464e8e8cbc0b9b9326

Also, the main source of truth is the LICENSE or COPYING file in the repo. Any contradictory statements in the README have no legal effect on the terms of the license, so, not conflicts. Use it like any other MIT project.

**Comment by YaroslavPodorvanov** [comment]
Everything is fine, there are no conflicts between the license and the terms of use.

If you want to add similar terms of use to your project, here’s an explanation why: https://tyrrrz.me/ukraine.

**Comment by donatj** [comment]
Not only does this project violate the terms of the MIT license. It also utilizes github.com/miku/zek which is itself GPL 3.0 - so the code itself can't even be considered actually MIT, this project is GPL 3.0 because of the terms of the GPL

This project is just a bunch of license violations
